### PR TITLE
Fixes authentication bug in Active Resource & adds various minor fixes

### LINKED ISSUE #2: Hook Up API

### LINKED ISSUE #19: scrollbar doesn't extend to top/bottom of FAQ question section
firefox 49 on linux

looks like it is leaving room for a small lil chevron row thing but no chevron is there

screenshot

### LINKED ISSUE #48: Favicon
Need a better favicon, the current one is too light

### LINKED ISSUE #50: state tracking issue in easter egg
click diamond, click "light is cool"

click diamond, click "Yeah dude" to forget the theme preference

site changes to dark theme; defaulting to light is expected.

### PR DESCRIPTION
**Pull request by bogdanpozderca**
Resolves #2 for Login
Also resolves #50 
Also resolves #48 
Also resolves #19

### CODE REVIEW

File: app/controllers/sessions_controller.rb [hunk 1]
```diff
@@ -10,6 +11,7 @@ def create
       session[:current_session] = session_response
       redirect_to root_url
     else
+      p session_response.errors.messages
```
Comment (milesjos) [inline app/controllers/sessions_controller.rb]: Lol
